name = "Akash Thota"
avatar = "images/me.jpg" # Avatar image. Default to "images/profile.webp".
bio = " Intrested about WEB 3.0 and Block Chain technologies"
company = "..."
location = "India"
# alternatives:
# location = "<a href='https://goo.gl/maps/UWFWsLdCp7AiXvWP7'>Visakhapatnam, India</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  # layout = "compact"
