email = "g00g1y5p4@gmail.com"
github = "g00g1y5p4"
linkedin = "g00g1y5p4"
twitter = "g00g1y5p4"
# facebook = "yourfacebookusername"
# gitlab = "yourgitlabusername"
# stackoverflow = "yourstackoverflowuserid"
# weibo = "yourweibousername"
# zhihu = "yourzhihuusername"
# instagram = "yourinstagramusername"
# quora = "yourquorausername"
# tumblr = "yourtumblrusername"
# reddit = "yourredditusername"
# telegram = "yourtelegramusername"
# qq = "yourqqnumber"
# dockerhub = "yourdockerhubusername"
# bitbucket = "yourbitbucketworkspaceid"
# kaggle = "yourkaggleusername"
# medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
# bilibili = "yourbilibiliuserid"
# youtube = "youryoutubechannelid"
discord = "g00g1y5p4"
# discourse = "https://yourforum.tld"
# facebookgroup = "yourfacebookgroupname"
# tiktok = "yourtiktokusername"
# pinterest = "yourpinterestusername"
